/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/videos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Videos */
        get: operations["list_videos_videos_get"];
        put?: never;
        /** Upload Video */
        post: operations["upload_video_videos_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/videos/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import Video
         * @description Register a video already on this machine without copying it (local use).
         */
        post: operations["import_video_videos_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/videos/{vid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Video */
        get: operations["get_video_videos__vid__get"];
        put?: never;
        post?: never;
        /** Delete Video */
        delete: operations["delete_video_videos__vid__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/videos/{vid}/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Video File
         * @description The video itself; FileResponse handles Range requests, so seeking works.
         */
        get: operations["video_file_videos__vid__file_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/videos/{vid}/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Job */
        post: operations["start_job_videos__vid__jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/videos/{vid}/jobs/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latest Job */
        get: operations["latest_job_videos__vid__jobs_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/videos/{vid}/jobs/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Job Stream
         * @description Server-sent events with the latest job state; closes when the job finishes.
         */
        get: operations["job_stream_videos__vid__jobs_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/videos/{vid}/stages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stages */
        get: operations["stages_videos__vid__stages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/videos/{vid}/ball": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ball Window
         * @description Ball positions between start and end seconds (whole video if end is omitted).
         */
        get: operations["ball_window_videos__vid__ball_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/videos/{vid}/players": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Player Window
         * @description Player boxes (image pixels) and court positions between start and end seconds.
         */
        get: operations["player_window_videos__vid__players_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/videos/{vid}/flights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Flights
         * @description 3D ball flights overlapping [start, end] seconds, with a court position for every frame.
         *     Videos with demo rallies get demo flights built from those rallies (source 'demo').
         */
        get: operations["flights_videos__vid__flights_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/videos/{vid}/ball/coverage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ball Coverage
         * @description Where tracking found the ball, summarised over the whole video (for the timeline's ball lane).
         */
        get: operations["ball_coverage_videos__vid__ball_coverage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/videos/{vid}/rallies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Rallies */
        get: operations["list_rallies_videos__vid__rallies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/videos/{vid}/rallies/{idx}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Correct Rally
         * @description Set (or clear, with null) the user's winner for one rally; returns all rallies with new scores.
         */
        patch: operations["correct_rally_videos__vid__rallies__idx__patch"];
        trace?: never;
    };
    "/videos/{vid}/actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Actions
         * @description Action events, shirt numbers per track and the tags they suggest (change add-player-actions).
         */
        get: operations["actions_videos__vid__actions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/videos/{vid}/actions/suggestions/{sid}/dismiss": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Dismiss Suggestion */
        post: operations["dismiss_suggestion_videos__vid__actions_suggestions__sid__dismiss_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/videos/{vid}/roster": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Roster */
        get: operations["get_roster_videos__vid__roster_get"];
        /**
         * Put Roster
         * @description Replace both teams' rosters; rejected (unchanged) when a number appears twice in a team.
         */
        put: operations["put_roster_videos__vid__roster_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/videos/{vid}/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Tags */
        get: operations["list_tags_videos__vid__tags_get"];
        put?: never;
        /**
         * Add Tag
         * @description Tag an attack or a serve; a number not on the roster is added to it. Returns all tags.
         */
        post: operations["add_tag_videos__vid__tags_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/videos/{vid}/tags/{tag_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Tag */
        delete: operations["delete_tag_videos__vid__tags__tag_id__delete"];
        options?: never;
        head?: never;
        /** Patch Tag */
        patch: operations["patch_tag_videos__vid__tags__tag_id__patch"];
        trace?: never;
    };
    "/videos/{vid}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Stats
         * @description Statistics from the tags and the current rallies (winner corrections included), computed on request.
         */
        get: operations["get_stats_videos__vid__stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActionEvent */
        ActionEvent: {
            /**
             * Action
             * @enum {string}
             */
            action: "block" | "receive" | "serve" | "set" | "spike";
            /** Track Id */
            track_id: number | null;
            /** Start S */
            start_s: number;
            /** End S */
            end_s: number;
            /** Peak Conf */
            peak_conf: number;
            /** Number */
            number: number | null;
            /** Team */
            team: ("a" | "b") | null;
        };
        /** ActionsOut */
        ActionsOut: {
            /** Events */
            events: components["schemas"]["ActionEvent"][];
            /** Numbers */
            numbers: components["schemas"]["ShirtNumber"][];
            /** Suggestions */
            suggestions: components["schemas"]["Suggestion"][];
        };
        /** BallCoverage */
        BallCoverage: {
            /** Duration S */
            duration_s: number;
            /** Coverage */
            coverage: number[];
        };
        /** BallWindow */
        BallWindow: {
            /** Fps */
            fps: number;
            /** Frame */
            frame: number[];
            /** X */
            x: (number | null)[];
            /** Y */
            y: (number | null)[];
        };
        /** Body_upload_video_videos_post */
        Body_upload_video_videos_post: {
            /** File */
            file: string;
        };
        /** Flight */
        Flight: {
            /** Start S */
            start_s: number;
            /** End S */
            end_s: number;
            /**
             * Source
             * @enum {string}
             */
            source: "model" | "demo";
            /**
             * Quality
             * @enum {string}
             */
            quality: "ok" | "low";
            /** Reasons */
            reasons: string[];
            /** Fit Px */
            fit_px: number | null;
            /** Start Speed Mps */
            start_speed_mps: number;
            /** Apex M */
            apex_m: number | null;
            net_crossing: components["schemas"]["NetCrossing"] | null;
            landing: components["schemas"]["Landing"] | null;
            /** Samples */
            samples: components["schemas"]["FlightSample"][];
            /**
             * Anchors
             * @default []
             */
            anchors: ("start" | "end")[];
            /**
             * Dropped
             * @default 0
             */
            dropped: number;
        };
        /** FlightSample */
        FlightSample: {
            /** T */
            t: number;
            /** X */
            x: number;
            /** Y */
            y: number;
            /** Z */
            z: number;
            /** Observed */
            observed: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImportRequest */
        ImportRequest: {
            /** Path */
            path: string;
        };
        /** Job */
        Job: {
            /** Id */
            id: string;
            /** Video Id */
            video_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "done" | "failed";
            /**
             * From Stage
             * @enum {string}
             */
            from_stage: "decode" | "court" | "ball" | "players" | "actions" | "trajectory" | "events" | "rallies";
            /** Stage */
            stage: ("decode" | "court" | "ball" | "players" | "actions" | "trajectory" | "events" | "rallies") | null;
            /** Progress */
            progress: number;
            /** Error */
            error: string | null;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
        };
        /** JobRequest */
        JobRequest: {
            /**
             * From Stage
             * @default decode
             * @enum {string}
             */
            from_stage: "decode" | "court" | "ball" | "players" | "actions" | "trajectory" | "events" | "rallies";
        };
        /** Landing */
        Landing: {
            /** X M */
            x_m: number;
            /** Y M */
            y_m: number;
        };
        /** NetCrossing */
        NetCrossing: {
            /** Height M */
            height_m: number;
            /** Y M */
            y_m: number;
        };
        /** PlayerBox */
        PlayerBox: {
            /** Frame */
            frame: number;
            /** Track Id */
            track_id: number;
            /** X1 */
            x1: number;
            /** Y1 */
            y1: number;
            /** X2 */
            x2: number;
            /** Y2 */
            y2: number;
            /** Interpolated */
            interpolated: boolean;
            /** Court X */
            court_x: number | null;
            /** Court Y */
            court_y: number | null;
            /** Side */
            side: ("a" | "b") | null;
            /** Team */
            team?: ("a" | "b") | null;
            /**
             * Role
             * @default player
             * @enum {string}
             */
            role: "player" | "other";
        };
        /** PlayerWindow */
        PlayerWindow: {
            /** Fps */
            fps: number;
            /** Placed */
            placed: boolean;
            /** Boxes */
            boxes: components["schemas"]["PlayerBox"][];
        };
        /** Rally */
        Rally: {
            /** Idx */
            idx: number;
            /** Start S */
            start_s: number;
            /** End S */
            end_s: number;
            /** Winner */
            winner: ("a" | "b") | null;
            /** Winner Override */
            winner_override: ("a" | "b") | null;
            /** Effective Winner */
            effective_winner: ("a" | "b") | null;
            /** Reason */
            reason: string | null;
            /** Confidence */
            confidence: number | null;
            /** Landing X */
            landing_x: number | null;
            /** Landing Y */
            landing_y: number | null;
            /**
             * Source
             * @enum {string}
             */
            source: "model" | "demo";
            score: components["schemas"]["Score"];
        };
        /** RallyPatch */
        RallyPatch: {
            /** Winner */
            winner: ("a" | "b") | null;
        };
        /** Roster */
        Roster: {
            /** Players */
            players: components["schemas"]["RosterPlayer"][];
        };
        /** RosterPlayer */
        RosterPlayer: {
            /**
             * Team
             * @enum {string}
             */
            team: "a" | "b";
            /** Number */
            number: number;
            /** Name */
            name?: string | null;
        };
        /** Score */
        Score: {
            /** Set No */
            set_no: number;
            /** A */
            a: number;
            /** B */
            b: number;
            /** Sets A */
            sets_a: number;
            /** Sets B */
            sets_b: number;
            /** Set Over */
            set_over: boolean;
        };
        /**
         * ScoreSummary
         * @description Score after the last rally, for the library list.
         */
        ScoreSummary: {
            /** Set No */
            set_no: number;
            /** A */
            a: number;
            /** B */
            b: number;
            /** Sets A */
            sets_a: number;
            /** Sets B */
            sets_b: number;
            /** Rallies */
            rallies: number;
            /** Corrected */
            corrected: number;
            /** Demo */
            demo: boolean;
        };
        /** ShirtNumber */
        ShirtNumber: {
            /** Track Id */
            track_id: number;
            /** Number */
            number: number | null;
            /** Share */
            share: number;
            /** Readings */
            readings: number;
        };
        /** StageInfo */
        StageInfo: {
            /**
             * Name
             * @enum {string}
             */
            name: "decode" | "court" | "ball" | "players" | "actions" | "trajectory" | "events" | "rallies";
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "done" | "todo" | "unavailable";
            /** Version */
            version?: string | null;
            /** Message */
            message?: string | null;
            /**
             * Summary
             * @default {}
             */
            summary: {
                [key: string]: unknown;
            };
        };
        /** StatLine */
        StatLine: {
            /**
             * Team
             * @enum {string}
             */
            team: "a" | "b";
            /** Number */
            number: number | null;
            /** Name */
            name: string | null;
            /** Set No */
            set_no: number | null;
            /** Attempts */
            attempts: number;
            /** Kills */
            kills: number;
            /** Attack Errors */
            attack_errors: number;
            /** Efficiency */
            efficiency: number | null;
            /** Kill Rate */
            kill_rate: number | null;
            /** Serves */
            serves: number;
            /** Aces */
            aces: number;
            /** Serve Errors */
            serve_errors: number;
            /** Unknown */
            unknown: number;
            /** Incomplete */
            incomplete: boolean;
        };
        /** Stats */
        Stats: {
            /** Lines */
            lines: components["schemas"]["StatLine"][];
            /** Rallies */
            rallies: number;
            /** Tagged Rallies */
            tagged_rallies: number;
            /** Outside */
            outside: number;
        };
        /**
         * Suggestion
         * @description A tag proposed from an action event; never counted until the coach posts it as a tag.
         */
        Suggestion: {
            /** Id */
            id: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "attack" | "serve";
            /** Time S */
            time_s: number;
            /** Team */
            team: ("a" | "b") | null;
            /** Number */
            number: number | null;
            /** Track Id */
            track_id: number | null;
            /**
             * Status
             * @enum {string}
             */
            status: "open" | "accepted" | "dismissed";
        };
        /** TagIn */
        TagIn: {
            /** Time S */
            time_s: number;
            /**
             * Kind
             * @enum {string}
             */
            kind: "attack" | "serve";
            /**
             * Team
             * @enum {string}
             */
            team: "a" | "b";
            /** Number */
            number: number;
            /** Outcome */
            outcome?: ("kill" | "ace" | "error" | "in_play") | null;
        };
        /** TagOut */
        TagOut: {
            /** Id */
            id: string;
            /** Time S */
            time_s: number;
            /**
             * Kind
             * @enum {string}
             */
            kind: "attack" | "serve";
            /**
             * Team
             * @enum {string}
             */
            team: "a" | "b";
            /** Number */
            number: number;
            /** Outcome */
            outcome: ("kill" | "ace" | "error" | "in_play") | null;
            /**
             * Effective Outcome
             * @enum {string}
             */
            effective_outcome: "kill" | "ace" | "error" | "in_play" | "unknown" | "outside";
            /** Inferred */
            inferred: boolean;
            /** Rally Idx */
            rally_idx: number | null;
        };
        /**
         * TagPatch
         * @description Fields to change; `outcome: null` clears the user's outcome (back to inferred).
         */
        TagPatch: {
            /** Time S */
            time_s?: number | null;
            /** Team */
            team?: ("a" | "b") | null;
            /** Number */
            number?: number | null;
            /** Outcome */
            outcome?: ("kill" | "ace" | "error" | "in_play") | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** Video */
        Video: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Fps */
            fps: number | null;
            /** Frames */
            frames: number | null;
            /** Width */
            width: number | null;
            /** Height */
            height: number | null;
            /** Created At */
            created_at: string;
            job: components["schemas"]["Job"] | null;
            score: components["schemas"]["ScoreSummary"] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_videos_videos_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Video"][];
                };
            };
        };
    };
    upload_video_videos_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_video_videos_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Video"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_video_videos_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Video"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_video_videos__vid__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Video"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_video_videos__vid__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    video_file_videos__vid__file_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_job_videos__vid__jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    latest_job_videos__vid__jobs_latest_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    job_stream_videos__vid__jobs_stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stages_videos__vid__stages_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StageInfo"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ball_window_videos__vid__ball_get: {
        parameters: {
            query?: {
                start?: number;
                end?: number | null;
            };
            header?: never;
            path: {
                vid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BallWindow"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    player_window_videos__vid__players_get: {
        parameters: {
            query?: {
                start?: number;
                end?: number | null;
            };
            header?: never;
            path: {
                vid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerWindow"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    flights_videos__vid__flights_get: {
        parameters: {
            query?: {
                start?: number;
                end?: number | null;
            };
            header?: never;
            path: {
                vid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Flight"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ball_coverage_videos__vid__ball_coverage_get: {
        parameters: {
            query?: {
                bins?: number;
            };
            header?: never;
            path: {
                vid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BallCoverage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_rallies_videos__vid__rallies_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rally"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    correct_rally_videos__vid__rallies__idx__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vid: string;
                idx: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RallyPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rally"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    actions_videos__vid__actions_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActionsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    dismiss_suggestion_videos__vid__actions_suggestions__sid__dismiss_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vid: string;
                sid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_roster_videos__vid__roster_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Roster"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_roster_videos__vid__roster_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Roster"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Roster"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_tags_videos__vid__tags_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_tag_videos__vid__tags_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_tag_videos__vid__tags__tag_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vid: string;
                tag_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_tag_videos__vid__tags__tag_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vid: string;
                tag_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TagPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TagOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_stats_videos__vid__stats_get: {
        parameters: {
            query?: {
                format?: "json" | "csv";
            };
            header?: never;
            path: {
                vid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description JSON, or CSV with format=csv */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Stats"];
                    "text/csv": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
