/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/videos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Videos */
        get: operations["list_videos_videos_get"];
        put?: never;
        /** Upload Video */
        post: operations["upload_video_videos_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/videos/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Import Video
         * @description Register a video already on this machine without copying it (local use).
         */
        post: operations["import_video_videos_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/videos/{vid}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Video */
        get: operations["get_video_videos__vid__get"];
        put?: never;
        post?: never;
        /** Delete Video */
        delete: operations["delete_video_videos__vid__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/videos/{vid}/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Video File
         * @description The video itself; FileResponse handles Range requests, so seeking works.
         */
        get: operations["video_file_videos__vid__file_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/videos/{vid}/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Job */
        post: operations["start_job_videos__vid__jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/videos/{vid}/jobs/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latest Job */
        get: operations["latest_job_videos__vid__jobs_latest_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/videos/{vid}/jobs/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Job Stream
         * @description Server-sent events with the latest job state; closes when the job finishes.
         */
        get: operations["job_stream_videos__vid__jobs_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/videos/{vid}/stages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stages */
        get: operations["stages_videos__vid__stages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/videos/{vid}/ball": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ball Window
         * @description Ball positions between start and end seconds (whole video if end is omitted).
         */
        get: operations["ball_window_videos__vid__ball_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/videos/{vid}/ball/coverage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ball Coverage
         * @description Where tracking found the ball, summarised over the whole video (for the timeline's ball lane).
         */
        get: operations["ball_coverage_videos__vid__ball_coverage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/videos/{vid}/rallies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Rallies */
        get: operations["list_rallies_videos__vid__rallies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/videos/{vid}/rallies/{idx}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Correct Rally
         * @description Set (or clear, with null) the user's winner for one rally; returns all rallies with new scores.
         */
        patch: operations["correct_rally_videos__vid__rallies__idx__patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** BallCoverage */
        BallCoverage: {
            /** Duration S */
            duration_s: number;
            /** Coverage */
            coverage: number[];
        };
        /** BallWindow */
        BallWindow: {
            /** Fps */
            fps: number;
            /** Frame */
            frame: number[];
            /** X */
            x: (number | null)[];
            /** Y */
            y: (number | null)[];
        };
        /** Body_upload_video_videos_post */
        Body_upload_video_videos_post: {
            /** File */
            file: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImportRequest */
        ImportRequest: {
            /** Path */
            path: string;
        };
        /** Job */
        Job: {
            /** Id */
            id: string;
            /** Video Id */
            video_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "done" | "failed";
            /**
             * From Stage
             * @enum {string}
             */
            from_stage: "decode" | "court" | "ball" | "events" | "rallies";
            /** Stage */
            stage: ("decode" | "court" | "ball" | "events" | "rallies") | null;
            /** Progress */
            progress: number;
            /** Error */
            error: string | null;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
        };
        /** JobRequest */
        JobRequest: {
            /**
             * From Stage
             * @default decode
             * @enum {string}
             */
            from_stage: "decode" | "court" | "ball" | "events" | "rallies";
        };
        /** Rally */
        Rally: {
            /** Idx */
            idx: number;
            /** Start S */
            start_s: number;
            /** End S */
            end_s: number;
            /** Winner */
            winner: ("a" | "b") | null;
            /** Winner Override */
            winner_override: ("a" | "b") | null;
            /** Effective Winner */
            effective_winner: ("a" | "b") | null;
            /** Reason */
            reason: string | null;
            /** Confidence */
            confidence: number | null;
            /** Landing X */
            landing_x: number | null;
            /** Landing Y */
            landing_y: number | null;
            /**
             * Source
             * @enum {string}
             */
            source: "model" | "demo";
            score: components["schemas"]["Score"];
        };
        /** RallyPatch */
        RallyPatch: {
            /** Winner */
            winner: ("a" | "b") | null;
        };
        /** Score */
        Score: {
            /** Set No */
            set_no: number;
            /** A */
            a: number;
            /** B */
            b: number;
            /** Sets A */
            sets_a: number;
            /** Sets B */
            sets_b: number;
            /** Set Over */
            set_over: boolean;
        };
        /**
         * ScoreSummary
         * @description Score after the last rally, for the library list.
         */
        ScoreSummary: {
            /** Set No */
            set_no: number;
            /** A */
            a: number;
            /** B */
            b: number;
            /** Sets A */
            sets_a: number;
            /** Sets B */
            sets_b: number;
            /** Rallies */
            rallies: number;
            /** Corrected */
            corrected: number;
            /** Demo */
            demo: boolean;
        };
        /** StageInfo */
        StageInfo: {
            /**
             * Name
             * @enum {string}
             */
            name: "decode" | "court" | "ball" | "events" | "rallies";
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "done" | "todo" | "unavailable";
            /** Version */
            version?: string | null;
            /** Message */
            message?: string | null;
            /**
             * Summary
             * @default {}
             */
            summary: {
                [key: string]: unknown;
            };
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** Video */
        Video: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Fps */
            fps: number | null;
            /** Frames */
            frames: number | null;
            /** Width */
            width: number | null;
            /** Height */
            height: number | null;
            /** Created At */
            created_at: string;
            job: components["schemas"]["Job"] | null;
            score: components["schemas"]["ScoreSummary"] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    list_videos_videos_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Video"][];
                };
            };
        };
    };
    upload_video_videos_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_video_videos_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Video"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_video_videos_import_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Video"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_video_videos__vid__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Video"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_video_videos__vid__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    video_file_videos__vid__file_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_job_videos__vid__jobs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["JobRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    latest_job_videos__vid__jobs_latest_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    job_stream_videos__vid__jobs_stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stages_videos__vid__stages_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StageInfo"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ball_window_videos__vid__ball_get: {
        parameters: {
            query?: {
                start?: number;
                end?: number | null;
            };
            header?: never;
            path: {
                vid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BallWindow"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ball_coverage_videos__vid__ball_coverage_get: {
        parameters: {
            query?: {
                bins?: number;
            };
            header?: never;
            path: {
                vid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BallCoverage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_rallies_videos__vid__rallies_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rally"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    correct_rally_videos__vid__rallies__idx__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                vid: string;
                idx: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RallyPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rally"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
